# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:18
from __future__ import unicode_literals

from django.db import migrations

def migrate(apps, editor):
    User = apps.get_model('auth', 'User')
    List = apps.get_model('boards', 'List')
    for u in User.objects.all():
        print(u)
        board = u.boards.first()
        if board: continue
        print('Creating board for', u.username)
        b = u.boards.create(name='My board')
        b.save()
        lists = (List(name='Propositions', board=b, position=0),
                 List(name='To try', board=b, position=1),
                 List(name='Accepted', board=b, position=2),
                 )
        [l.save() for l in lists]


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('boards', '0003_list_name'),
    ]

    operations = [
        migrations.RunPython(migrate, reverse_code=migrations.RunPython.noop)
    ]
