# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='temp title', max_length=200),
            preserve_default=False,
        ),
    ]
