# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_song_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
