# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20170605_1713'),
        ('boards', '0007_auto_20170605_1539'),
    ]

    operations = [
    ]
