# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_song_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-score']},
        ),
        migrations.AlterField(
            model_name='song',
            name='link',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
